<?php
if (($this->blockIsVisible())) {
    $pickup_point = $this->getTerminalName();
    if ($this->isHrxTerminal()) {
        $button = '<button id = "hrx-change-terminal" class = "action-secondary">' . __('Change') . '</button>';
        if ($this->getMagentoVersion() >= 2.2) {
            echo '<div style = "margin-bottom: 30px;">';
        } else {
            echo '<div style = "margin-top: 20px;margin-bottom: 30px;">';
        }
        echo '<div class ="admin__page-section-title"><span class = "title">' . __("HRX delivery") . '</span></div>'; //.$pickup_point ;
        echo '<div style = "margin-bottom: 10px;"><b>'.__("Terminal").'</b></div>';
        if ($this->getOrder()->getStatus() == "closed" || $this->getOrder()->getStatus() == "complete") {
            echo $pickup_point ?? '-' . '</div>';
        } else {
            ?>
            <?php $locs = $this->getTerminals($this->getOrder()); ?>
            <?php $current_terminal = $this->getCurrentTerminal(); ?>
            <select name = "order[hrx_pickup_point]" id = "hrx_parcel_terminal_list" data-url = '<?= $this->getUrl('hrx/order/UpdateTerminal') ?>' data-order = '<?= $this->getOrder()->getId(); ?>' style = "display: inline; height: 32px;">
                <option value = ""><?php echo __('Select parcel terminal');?></option>
                <?php
                $grouped_options = array();

                foreach ($locs as $loc) {
                    $key = $loc['terminal_id'];
                    if (!isset($grouped_options[(string) $loc['city']])) {
                        $grouped_options[(string) $loc['city']] = array();
                    }
                    $grouped_options[(string) $loc['city']][(string) $key] = $loc;
                }
                ksort($grouped_options);
                foreach ($grouped_options as $city => $locs) {
                    echo '<optgroup label = "' . $city . '">';
                    foreach ($locs as $key => $loc) {
                        echo '<option value = "' . $key . '" ' . ($key == $current_terminal ? 'selected' : '') . '>' . $loc['address'] . ', ' . $loc['city'] . '</option>';
                    }
                    echo '</optgroup>';
                }
                ?>
            </select>   
            <?php
            echo $button;
            echo '</div>';
        }
    }
}
?>