
<?php
$orders = $this->getOrders();
if ($this->getMagentoVersion() < '2.3.0') {
    $old_version = true;
} else {
    $old_version = false;
}
if (count($orders)):
    $items_ignore = array();
    $p_limit = 10;
    $total_pages = ceil(count($orders) / $p_limit);
    $current_page = 1;

    if (isset($_GET['p'])) {
        $current_page = $_GET['p'];
    }
    if ($current_page > $total_pages) {
        $current_page = $total_pages;
    }
    $counter = 0;
    ?>
    <?php
    if ($total_pages > 1) {
        $data = '<div class="pagination">';
        $data .= ' <a href="?p=1" style = "padding:5px 8px;border:1px solid #000;">«</a>';
        $start = 1;
        if ($current_page > 5) {
            $start = $current_page - 2;
        }
        $end = $start + 5;
        if ($end > $total_pages) {
            $end = $total_pages;
        }
        for ($i = $start; $i <= $end; $i++) {
            $data .= '<a href="?p=' . $i . '"  style = "padding:5px 8px;border:1px solid #000;' . ($current_page == $i ? 'background-color:#303030;color:#ffffff;' : '') . '">' . $i . '</a>';
        }
        $data .= '<a href="?p=' . $total_pages . '" style = "padding:5px 8px;border:1px solid #000;">»</a>';
        $data .= '</div>';
        echo $data;
    }
    ?>
        <div id = "hrx-messages"></div>
        <br/>
        <div class = "grid">
            <table class="data-grid">
                <thead>
                    <tr >
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><input type = "checkbox"  class = "check-all"/></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Order #'); ?></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Order status'); ?></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Delivery type'); ?></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Parcel terminal'); ?></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Warehouse'); ?></span></th>
                        <th class = "data-grid-th"><span class="data-grid-cell-content"><?php echo __('Tracking'); ?></span></th>
                        <th class = "data-grid-th" style = "min-width:150px;"></th>
                        <th class = "data-grid-th"></th>
                    </tr>
                </thead>
                <tbody>
                    <?php $_odd = ''; ?>
                    <?php $counter = 0; ?>
                    <?php foreach ($orders as $order): ?>
                        <?php $counter++; ?>
                        <?php 
                        if ($counter <= ($current_page - 1) * $p_limit) {
                            continue;
                        }
                        if ($counter > ($current_page - 1) * $p_limit + $p_limit) {
                            break;
                        }
                        ?>
                        <tr class = "data-row">
                            <?php
                            $order_items = array();
                            $ids = $order->getId();
                            $hrx_order = $this->getHrxOrder($order);
                            ?>
                            <td><div class = "data-grid-cell-content"><input type = "checkbox" name = "items[]" class = "manifest-item" value = "<?php echo $ids; ?>"/></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $order->getIncrementId(); ?></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $this->getStatus($hrx_order); ?></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $this->getDeliveryType($order); ?></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $this->getTerminal($hrx_order); ?></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $this->getWarehouse($hrx_order); ?></div></td>
                            <td><div class = "data-grid-cell-content"><?php echo $this->getTracking($hrx_order); ?></div></td>
                            <td><div class = "data-grid-cell-content text-center"><?php echo $this->getOrderActions($hrx_order); ?></div></td>
                            <td><div class = "data-grid-cell-content text-center"><?php echo $this->getOrderEdit($hrx_order); ?></div></td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    <?php echo $this->getPagerHtml(); ?>
    <div>
        <br/>
        <div class="f-left">
            <button title="<?php echo __('Register'); ?>" type="button" class="hrx-btn mass-action" data-action = "register">
                <?php echo __('Register'); ?>
            </button> 
            <button title="<?php echo __('Print labels'); ?>" type="button" class="hrx-btn btn-outline mass-action" data-action = "label">
                <?php echo __('Print labels'); ?>
            </button>    
            <button title="<?php echo __('Print return labels'); ?>" type="button" class="hrx-btn btn-outline mass-action" data-action = "return_label">
                <?php echo __('Print return labels'); ?>
            </button>   
            <button title="<?php echo __('Mark as ready'); ?>" type="button" class="hrx-btn mass-action" data-action = "ready">
                <?php echo __('Mark as ready'); ?>
            </button>   
            <span class = "v-divider"></span>
            <button title="<?php echo __('Delete orders'); ?>" type="button" class="hrx-btn btn-outline mass-action" data-action = "delete">
                <?php echo __('Delete orders'); ?>
            </button> 
        </div>
        <div class="f-clear"></div>
    </div>
    <script>
        require(['jquery'], function ($) {
            $('document').ready(function () {
                $('.single-action').on('click', function () {
                    var ids = $(this).attr('data-id');
                    var action = $(this).attr('data-action');
                    doAction(action, ids);
                });
                $('.mass-action').on('click', function () {
                    var action = $(this).attr('data-action');
                    var ids = "";
                    $('.manifest-item:checked').each(function () {
                        ids += $(this).val() + ";";
                        var id = $(this).val();
                    });
                    if (ids == "") {
                        alert('<?php echo __('Select orders'); ?>');
                    } else {
                        doAction(action, ids);
                    }
                });
                $('.check-all').on('click', function () {
                    var checked = $(this).prop('checked');
                    $(this).parents('table').find('.manifest-item').each(function () {
                        $(this).prop('checked', checked);
                    });
                });
            });

            function doAction(action, ids) {
                <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $key_form = $objectManager->get('Magento\Framework\Data\Form\FormKey');
                $form_Key = $key_form->getFormKey(); 
                ?>
                
                $("#hrx-messages").html('');
                var formKey = "<?php echo $form_Key; ?>";
                var ajaxRequest;
                    var form = $('#hrx-order-form')[0];
                    var data = new FormData(form);
                    ajaxRequest = jQuery.ajax({
                        url: "<?php echo $this->getUrl('hrx/order/action'); ?>",
                        type: 'POST',
                        data: {action: action, ids: ids, form_key: formKey},
                        beforeSend: function () {
                            jQuery('#loader').show();
                        }
                    });
                        //Show successfully for submit message
                    ajaxRequest.done(function (response, textStatus, jqXHR) {
                        if (typeof response.pdf !== 'undefined') {
                            var byteCharacters = atob(response.pdf);
                            var byteNumbers = new Array(byteCharacters.length);
                            for (var i = 0; i < byteCharacters.length; i++) {
                                byteNumbers[i] = byteCharacters.charCodeAt(i);
                            }
                            var byteArray = new Uint8Array(byteNumbers);
                            var file = new Blob([byteArray], { type: 'application/pdf;base64' });
                            var fileURL = URL.createObjectURL(file);
                            const url = URL.createObjectURL(file);
                            const a = document.createElement('a');
                            //a.download = 'test.pdf';
                            a.href = url;
                            a.target = '_blank';

                            a.click();

                            setTimeout(function () {
                                a.remove();
                                URL.revokeObjectURL(url);
                            }, 100);
                        } else {
                            if (typeof response.status !== 'undefined' && response.status == 'ok') {
                                $("#hrx-messages").append('<div class = "hrx-ok">Done. Refreshing in 3 seconds ...</div>');
                                setTimeout(function(){ location.reload(); }, 3000);
                            }
                        }
                        if (typeof response.messages !== 'undefined' ) {
                            $(response.messages).each(function(index,msg) {
                                $("#hrx-messages").append('<div class = "hrx-error">'+msg+'</div>');
                            });
                        }
                        
                        //$('#loader').hide();
                    });

                        //On failure of request this function will be called
                    ajaxRequest.fail(function () {
                        //show error
                        //$('#loader').hide();
                    });
            }
        });
    </script>
<?php else: ?>
    <p><?php echo __('No assign shipments found'); ?></p>
<?php endif;