<?php $locs = $this->getTerminals(); ?>
<?php $current_terminal = $this->getCurrentTerminal(); ?>
<select name = "order[hrx_pickup_point]" id = "hrx_parcel_terminal_list" onchange="order.setParcelTerminal(this.value)" style = "width:100%; display: none;">
                          <option value = "">Select parcel terminal</option>
                          <?php
                          
                          $grouped_options = array();
                          
                          foreach ($locs as $loc){
                            $key = $loc->ZIP;
                            if (!isset($grouped_options[(string)$loc->A3_NAME]))
                              $grouped_options[(string)$loc->A3_NAME] = array();
                            $grouped_options[(string)$loc->A3_NAME][(string)$key] = $loc;
                            
                         }
                         ksort($grouped_options);
                          foreach ($grouped_options as $city=>$locs){
                            echo '<optgroup label = "'.$city.'">';
                            foreach ($locs as $key=>$loc){
                              echo '<option value = "'.$key.'" '.($key == $current_terminal?'selected':'').'>'.$loc->NAME.', '. $loc->A2_NAME .', '. $loc->A0_NAME .'</option>';
                            }
                            echo '</optgroup>';
                          }
                          
                          ?>
                        </select>
<script>     
jQuery('#hrx_parcel_terminal_list').insertAfter(jQuery('#s_method_hrx_parcel_terminal').parent()).show();

</script>